---
title: Scope der Erweiterung der Schnittstellen für SchulConneX um die Schnittstellen für Nutzungsrechte und Zugriffsinformationen (Highlevel)
---
flowchart TD
    %% --- --- --- --- ---
    %% Entities
    %% --- --- --- --- ---
    subgraph Lizenzverwaltungssystem
    LZI(Lizenz-Zuweisung \n intern)
    end
    subgraph Schnittstelle
    API[API Schnittstelle \n /lizenz-info]
    end
    subgraph Consumer
    LZE(Lizenz-Zuweisung \n extern / API)
    end
    subgraph ODRL Type
    Agreement(Agreement)
    Set(Set)
    Ticket(Ticket)
    end
    %% --- --- --- --- ---
    %% Relations
    %% --- --- --- --- ---
    API-.Filter über Person / \n Gruppenzugehörigkeit.->LZI
    LZI-.Entfernen \n persönlicher Daten.->API
    LZE-.Anfrage Nutzungsrechte und \n Zugriffsinformationen.->API
    API-.Nutzungsrechte und \n Zugriffsinformationen.->LZE
    LZI-.Typ.-Set
    LZE-.Typ.-Set
    %% --- --- --- --- ---
    %% Styling
    %% --- --- --- --- ---
    Lizenzverwaltungssystem ~~~ Schnittstelle ~~~ Consumer
