sequenceDiagram
    actor User
    participant BP as Bildungsplattform
    participant LS as IAM
    participant LK as Lizenzkomponente
    participant A as Anwendung

    User->>BP: Login
    BP->>LS: GET /person-info
    LS-->>BP: 
    BP->>LK: GET /policies-info
    LK-->>BP: 
    User->>BP: Aufruf Medienregal
    Note over BP: Medienregal<br/>(LTI-)Links zu den<br/>verfügbaren Anwendungen
    User->>BP: Aufruf Anwendung
    BP->>A: (LTI-)Launch inkl uid
    activate A
    A->>LS: SSO-Auth, Access Token
    A->>LS: GET /person-info
    LS-->>A: 
    A->>LK: GET /lizenz-zugriffsinfo/{lizenzInfoUid}
    LK-->>A: 
    Note over A: Validierung Lizenzschlüssel
    User->>A: Logout
    A->>A: Logout
    A->>BP: Zurück zum LMS
    deactivate A 