openapi: '3.0.2'
info:
  title: Schulconnex
  version: '1.6'
  description: |
    Beschreibung der Schnittstellen von Schulconnex f체r Dienste
  contact:
    name: 'FWU Institut f체r Film und Bild in Wissenschaft und Unterricht gemeinn체tzige GmbH'
    url: https://www.fwu.de/
  license:
    name: Creative Commons Attribution-NoDerivatives 4.0 International (CC BY-ND 4.0)
    url: https://creativecommons.org/licenses/by-nd/4.0/legalcode
servers:
  - url: https&zwj;://schulconnex.test/v1
    description: Lokaler Testserver
security:
  - oAuthForServices: []
  - oAuthForUser: []
tags:
  - name: Organisationen
    description: Schulen oder sonstige relevante Organisationen
  - name: Personen
    description: Alles zu Personen und Personendatens채tzen
paths:
  /person-info:
    $ref: './paths-person-info.yaml'
  /personen-info:
    $ref: './paths-personen-info.yaml'
  /organisationen-info:
    $ref: './paths-organisationen-info.yaml'
components:
  securitySchemes:
    oAuthForServices:
      $ref: './securitySchema-oAuthForServices.yaml'
    oAuthForUser:
      $ref: './securitySchema-oAuthForUser.yaml'
