openapi: '3.0.2'
info:
  title: Schulconnex
  version: '1.5'
  description: |
    Beschreibung der Schnittstellen von Schulconnex für Dienste
  contact:
    name: 'Landesinitiative n-21: Schulen in Niedersachsen online e. V.'
    url: https://www.n-21.de/
  license:
    name: Creative Commons Attribution-NoDerivatives 4.0 International (CC BY-ND 4.0)
    url: https://creativecommons.org/licenses/by-nd/4.0/legalcode
servers:
  - url: https://schulconnex.test/v1
    description: Lokaler Testserver
security:
  - oAuthForServices: []
  - oAuthForUser: []
tags:
  - name: Organisationen
    description: Schulen oder sonstige relevante Organisationen
  - name: Personen
    description: Alles zu Personen und Personendatensätzen
paths:
  /person-info:
    $ref: './paths-person-info.yaml'
  /personen-info:
    $ref: './paths-personen-info.yaml'
  /organisationen-info:
    $ref: './paths-organisationen-info.yaml'
  /policies-info:
    $ref: './paths-policies-info.yaml'
components:
  securitySchemes:
    oAuthForServices:
      $ref: './securitySchema-oAuthForServices.yaml'
    oAuthForUser:
      $ref: './securitySchema-oAuthForUser.yaml'
