openapi: '3.0.2'
info:
  title: Schulconnex
  version: '1.5'
  description: |
    Beschreibung der Schnittstellen von Schulconnex für Quellsysteme
  contact:
    name: 'Landesinitiative n-21: Schulen in Niedersachsen online e. V.'
    url: https://www.n-21.de/
  license:
    name: Creative Commons Attribution-NoDerivatives 4.0 International (CC BY-ND 4.0)
    url: https://creativecommons.org/licenses/by-nd/4.0/legalcode
servers:
  - url: https://schulconnex.test/v1
    description: Lokaler Testserver
security:
  - oAuthForServices: []
tags:
  - name: Personen
    description: Alles zu Personen und Personendatensätzen
  - name: Organisationen
    description: Schulen oder sonstige relevante Organisationen
  - name: Gruppen
    description: Zusammenfassung von mehreren Personen
  - name: Sichtfreigaben
    description: Regelt zeitliche Sichtfreigabe für Organisationen
  - name: Personenkontexte
    description: Gibt Rolle, Schule bzw. Organisation an
  - name: Beziehungen
    description: Beziehung zwischen Personenkontexten
  - name: Gruppenzugehörigkeiten
    description: Verknüpfung von Personenkontext und Gruppe
paths:
  /personen:
    $ref: './paths-personen.yaml'
  /personen/{id}:
    $ref: './paths-personen-id.yaml'
  /personen/{id}/personenkontexte:
    $ref: './paths-personen-id-personenkontexte.yaml'
  /personenkontexte:
    $ref: './paths-personenkontexte.yaml'
  /personenkontexte/{id}:
    $ref: './paths-personenkontexte-id.yaml'
  /personenkontexte/{id}/beziehungen:
    $ref: './paths-personenkontexte-id-beziehungen.yaml'
  /personenkontexte/{id}/sichtfreigaben:
    $ref: './paths-personenkontexte-id-sichtfreigaben.yaml'
  /beziehungen/{id}:
    $ref: './paths-beziehungen-id.yaml'
  /organisationen:
    $ref: './paths-organisationen.yaml'
  /organisationen/{id}:
    $ref: './paths-organisationen-id.yaml'
  /organisationen/{id}/organisationsbeziehungen:
    $ref: './paths-organisationen-id-organisationsbeziehungen.yaml'
  /organisation-info:
    $ref: './paths-organisation-info.yaml'
  /gruppen:
    $ref: './paths-gruppen.yaml'
  /gruppen/{id}:
    $ref: './paths-gruppen-id.yaml'
  /gruppen/{id}/gruppenzugehoerigkeiten:
    $ref: './paths-gruppen-id-gruppenzugehoerigkeiten.yaml'
  /gruppenzugehoerigkeiten:
    $ref: './paths-gruppenzugehoerigkeiten.yaml'
  /gruppenzugehoerigkeiten/{id}:
    $ref: './paths-gruppenzugehoerigkeiten-id.yaml'
  /sichtfreigaben/{id}:
    $ref: './paths-sichtfreigaben-id.yaml'
components:
  securitySchemes:
    oAuthForServices:
      $ref: './securitySchema-oAuthForServices.yaml'
    oAuthForUser:
      $ref: './securitySchema-oAuthForUser.yaml'
