openapi: '3.0.2'
info:
  title: Schulconnex
  version: '1.6'
  description: |
    Beschreibung der Schnittstellen von Schulconnex für Nuztungsrechte
  contact:
    name: 'Landesinitiative n-21: Schulen in Niedersachsen online e. V.'
    url: https://www.n-21.de/
  license:
    name: Creative Commons Attribution-NoDerivatives 4.0 International (CC BY-ND 4.0)
    url: https://creativecommons.org/licenses/by-nd/4.0/legalcode
servers:
  - url: https://schulconnex.test/v1
    description: Lokaler Testserver
security:
  - oAuthForServices: []
  - oAuthForUser: []
# tags:
#   - name: Organisationen
#     description: Schulen oder sonstige relevante Organisationen
paths:
  /policies-info:
    $ref: './paths-policies-info.yaml'
components:
  securitySchemes:
    oAuthForServices:
      $ref: './securitySchema-oAuthForServices.yaml'
    oAuthForUser:
      $ref: './securitySchema-oAuthForUser.yaml'
